version: '3.9'

services:
  app:
    image: ${DOCKER_USERNAME}/play-hive-chat:latest # 사용할 이미지 이름
    build:
      context: . # Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile # 빌드에 사용할 Dockerfile
    ports:
      - "8080:8080" # 호스트와 컨테이너의 포트 매핑
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    restart: always