spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_ENDPOINT}:6543/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: postgres.vicajgpdbhjueqmakcme
    password: ${DB_PASSWORD}

  second-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${SECOND_DB_ENDPOINT}:3306/${SECOND_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: playhive
    password: ${SECOND_DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}

logging:
  level:
    root: info  # 전체 로그를 INFO, DEBUG, WARN 수준으로 설정
    org.springframework.security: warn
    org.springframework.web: warn
    com.myteam.server: info
    # 필요 시 특정 SQL 로그를 추가하거나 Hibernate SQL 로그를 설정
    hibernate.SQL: warn
    org.springframework.boot.autoconfigure: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: WARN
    # 아직 Thymeleaf 를 사용하지 않기 때문에, 경고 메세지를 제거합니다.
    spring.thymeleaf.check-template-location: false
    org.hibernate.type: INFO

jwt:
  issuer: myteam.org
  secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
