spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_ENDPOINT}:6543/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: postgres.vicajgpdbhjueqmakcme
    password: ${DB_PASSWORD}

  second-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${SECOND_DB_ENDPOINT}:3306/${SECOND_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: playhive
    password: ${SECOND_DB_PASSWORD}

jwt:
  issuer: myteam.org
  secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

