spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ENDPOINT}:6543/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: postgres.vicajgpdbhjueqmakcme
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 1000 #??? ??
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update
      #  create	?????? ???? ?? ??
      #  create-drop ?????? ???? ????. ?? ??? ?????
      #  update	??? ??? ?? (?? DB ?? ??X)
      #  validate Entity ? ???? ?? ?? ???? ??
      #  none ?????? ? ?? ???? ??.
    open-in-view: true

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}
